### ISSUE TITLE
Suggestion for stick variants

### ISSUE THREAD

**Issue by JayCeeCreates** [MrFantiVideo/MineGate#1]
I would like to suggest that the stick variants (spruce, birch, etc.) be added to common tags for better compatibility with several mods that add tools. Your response would be greatly appreciated-

**Comment by MrFantiVideo** [comment]
Hello,

Can you clarify for me what you mean by « common tags » ?
It seems to me that I have already modified the « sticks.json » file in order to make all sticks compatible with all crafts.

**Comment by JayCeeCreates** [comment]
Now put that sticks.json to resources\data\c\tags\items

**Comment by MrFantiVideo** [comment]
I change this in the new version. ([MoreBlocks 1.1.3](https://github.com/MrFantiVideo/MineGate/releases/tag/1.1.3))
Can you confirm for me that this is what you want?

**Comment by JayCeeCreates** [comment]
Created a pull request which does what I'm talking about-

**Comment by MrFantiVideo** [comment]
I would just like to understand why you want to use « c » and what does that change?
Do other mods also use this way? or the Fabric documentation says something about it that I haven't seen?

Thanks in advance, otherwise I could put all of this in place after my exams.

**Comment by JayCeeCreates** [comment]
One of the sole reasons I can give is that someone using our mods (EarlyGame and MineGate) found out that using your modded sticks to craft my modded tools doesn't work. The same happened with All The Blocks You Want. This is to ensure compatibility with mods that add modded tools so that the recipes use the common stick tag.

It's like having a modded copper ingot be added to common copper ingot tag so that mods with modded copper tools can use c:copper_ingots.

I hope you understand-

**Comment by JayCeeCreates** [comment]
https://fabricmc.net/wiki/tutorial:tags#creating_new_common_tags
This can help in understanding common tags

**Comment by MrFantiVideo** [comment]
Thanks for the link to the documentation!
I understand better why the use « c », this modification will be present in the next version of the mod.

(Sorry for the time to understand, it's not always easy to translate correctly from English to French...)

**Comment by MrFantiVideo** [comment]
Modification present in version [1.1.5](https://github.com/MrFantiVideo/MineGate/releases/tag/1.1.5) of mod.
Thank you for your contribution.
