### ISSUE TITLE
Dirt slabs cannot grow grass

### ISSUE THREAD

**Issue by BlueThunderFox** [MrFantiVideo/MineGate#10]
Dirt slabs do not grow grass when full size grass blocks are adjacent to them.

**Comment by MrFantiVideo** [comment]
Hello,

Can you illustrate the problem? Are you on the latest version?

**Comment by BlueThunderFox** [comment]
I can set up a couple of experiments and get back to you with pictures

**Comment by Timolino456** [comment]
I believe this is want they mean. MineGate dirt slabs don't grow grass, even with high TickSpeed nothing happens.
For comparison Consistency+'s dirt slabs next to them, which do grow grass regularly

![2021-10-06_15 28 00](https://user-images.githubusercontent.com/38137599/136211655-82363eb5-bc83-4b00-bb60-ae54de8c6f40.png)

**Comment by MrFantiVideo** [comment]
It seems to work if it's a slab of grass.
So I have to see to correct this when it comes to a block of grass nearby.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.1](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.1))
