### ISSUE TITLE
Wood Cutter blade spins both directions, depending on which side you are on (Stone Cutter is fine)

### ISSUE THREAD

**Issue by BlueThunderFox** [MrFantiVideo/MineGate#11]
When you look at each side of the Wood Cutter, the blade spins different directions on each side.  Compare this to the Stone Cutter, which does not.

Recommended fix: Mirror one side of the Wood Cutter blade animation.

**Comment by BlueThunderFox** [comment]
The wood cutter can also only be crafted with Oak wood, and not other types of wood.  This seems incorrect, am I right?

**Comment by MrFantiVideo** [comment]
Hello,

I'll see what I can do about the minor visual issue.
The stonecutter can only be crafted with stone, so it will be the same with the woodcutter, only with oak wood.

**Comment by MrFantiVideo** [comment]
I have found the cause of this problem and I will see to correct it.

**Comment by MrFantiVideo** [comment]
Hello,

I have look on my side and I don't have the problem.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.1.3](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.0))
