### ISSUE TITLE
Villagers don't recognize quarters and eighths as obstacles and get stuck

### ISSUE THREAD

**Issue by Timolino456** [MrFantiVideo/MineGate#17]
This might also affect other mobs, but I only observed it with villagers so far.

The villager here tries to walk to a bed and can't because a wall made of a quarter and an eighth is in the way, but it doesn't seem to notice and doesn't walk around it.

Edit: accidentally wrote vertical slab although it's a quarter in the screenshot
![2021-10-06_15 14 42](https://user-images.githubusercontent.com/38137599/136209830-6bf3f70f-d6be-49a4-9af7-0461954429d5.png)

**Comment by MrFantiVideo** [comment]
Hello,

I will inquire about this problem, if you have any ideas to solve the problem, please do not hesitate.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.0](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.0))
