### ISSUE TITLE
Snow turns transparent

### ISSUE THREAD

**Issue by cryxli** [MrFantiVideo/MineGate#2]
### Observation

Snow covers are half transparent.

![MineGate Issue](https://i.imgur.com/Bv4uJ2z.png)

or see https://imgur.com/a/t2kwpDD

Note: The screenshot was taken with more mods enabled, but it can be reproduced with the minimum setup, below.

This does not happen with MineGate 1.1.1. Therefore, I assume MineGate must cause it.

### Setup

- Minecraft 1.16.5
- Fabric API 0.34.2
- MineGate 1.1.2

### Reproduction

Create a new world and look for snow covered mountains.

**Comment by MrFantiVideo** [comment]
Thanks for your feedback.
Fixed in the new version. ([MoreBlocks 1.1.3](https://github.com/MrFantiVideo/MineGate/releases/tag/1.1.3))
