### ISSUE TITLE
Snow blocks are fully rendered all of the time

### ISSUE THREAD

**Issue by ShepBoi** [MrFantiVideo/MineGate#20]
My friend and I run a minecraft server and the players on our server were having severe perfomance issues when going into chunks with lots of snow blocks (e.g mountains), and when we went into spectator we realised that snow blocks were fully rendered, and removing MineGate solved the issue. Please fix this as we think it's an excellent mod with lots of block variety.

**Comment by Gilbertato** [comment]
I found out the problem to this error,
Also I am that friend who runs a minecraft server,

What you need to do is open the jar file
go into assets > minecraft > models > block.
then delete all the files in there that start with snow.
I tried this and now the snow 6 side glitch is gone.

**Comment by MrFantiVideo** [comment]
Hello,

I'm going to take a look, because if I'm modifying the game files it's to be able to put the snow blocks on grass slabs.
It is possible that my files are not optimizing too.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.0](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.0))
