### ISSUE TITLE
Suggestion: is it possible to disable the world gen stuff in settings

### ISSUE THREAD

**Issue by EGOIST1372** [MrFantiVideo/MineGate#22]
is it possible to disable the world gen stuff in settings for those who only want to add extra decorative blocks to their game and don't want new ores and such world gen stuff?!
with this option many people are going to use this mod because high versatility for different tastes and options to choose
thanks in advance

**Comment by MrFantiVideo** [comment]
Hello,

Available with [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) or in « .minecraft/config/minegate.json » by putting the option « useMixins » or « generationOres » on false. If you have other questions, do not hesitate.
