### ISSUE TITLE
Would love a 1.18.2 update when you have time!

### ISSUE THREAD

**Issue by greensad** [MrFantiVideo/MineGate#24]

**Comment by MrFantiVideo** [comment]
Hello,

I am currently working on version 1.18.2 of the mod which adds and corrects a lot of things.
I plan to publish a « beta » or finish version very soon.

**Comment by MrFantiVideo** [comment]
She's there ! ([MoreBlocks 1.2.0](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.0))

**Comment by greensad** [comment]
thank fant
