### ISSUE TITLE
Some way to generate Tile.

### ISSUE THREAD

**Issue by campbebj** [MrFantiVideo/MineGate#3]
Previously we could get tile by cooking blackstone, now we dont have any way except mining the new ore. Im playing skyblock so i dont have any ore and everything i do is farmed. id love some way to get tile again by cooking something, perhaps cooking blackstone again, where blackstone cooked generates single tiles (similar to how netherrack cooked generates netherbricks?)

**Comment by MrFantiVideo** [comment]
I don't remember modifying any crafts related to minerals, but I note the idea for the future.

**Comment by MrFantiVideo** [comment]
It is now possible with version [1.1.5](https://github.com/MrFantiVideo/MineGate/releases/tag/1.1.5) to have tiles without having the ores.
If you put a block of deepslate tiles in a stonecutter, it will give you the option of having 4 tiles.

Thank you for your contribution.
