### ISSUE TITLE
World and generation are stuck when updating minegate 1.2.0 to 1.2.1

### ISSUE THREAD

**Issue by KamassKeep** [MrFantiVideo/MineGate#30]
Hello MrFantiVideo

First i love your mods, you do great job.

i play on the modpack medieval minecraft with other mod that i implemented (sorry for my english), if you want the list, say me.

I was on my new .minecraft that was updating with your new 1.2.1 minegate, i had to update because of crop and other plant that cause crash, and eventually piston and observer that didn't work.

so after that i play on my world and it's work well, but when i want to create a new world it doesn't work, and my actual world stuck on generation so i have litteraly chunk being render but all are invisible block after the border of my world.

Problem is that i don't know how to report a crash, because, there isn't. 

If you want to know i have try a backup of my .minecraft just before updating to 1.2.1, so i have try to generate just before that and it's work, and just after i retry to update minegate without delete the mixinfile and the game won't generate anymore.

I hope you understand, because of my bad english.

Have good luck

**Comment by MrFantiVideo** [comment]
Hello,

I understood the problem very well and it will be solved in the next version.
She will be available very soon.

Don't worry about English, I'm French and I have the same problem.

**Comment by KamassKeep** [comment]
Okay perfect, I am also french and thank you for all your work, really incredible.

Do yo think that i can still play on my world without generate, so i wil play more on the center of my map, and when you will update the mod i will add the new version for my world?

Yes my question is boring, but if you have the same problem, i think you have the answer.

Have good day my friend

**Comment by MrFantiVideo** [comment]
I have doubts, I invite you to test with this version:  [MoreBlocks 1.2.2-dev-3](https://libraries.minegate.fr/maven/net/minegate/fr/minegate-moreblocks/1.2.2-dev-3/minegate-moreblocks-1.2.2-dev-3.jar)

**Comment by KamassKeep** [comment]
Ok man i have good news,

 i have try all my backups of .minecraft, 
all are working properly, this mean that any version of minegate (1.2.0, 1.2.1dev, and 1.2.1) can be updating with this new update that you gave me.

The generation is repair, maybe i can contact you in another place, i have see little bug-texture with journeymap when  entering the world, nothing so bad but i can show you if you want.

Merci beaucoup je ne sais pas combien de temps tu passe sur ce mod, j'éspère que Mojang verra ca que tu fais.

**Comment by MrFantiVideo** [comment]
Perfect ! I would like you to show me the bug of the texture in question if possible.

It is I who thank you for using my mod. :)

**Comment by KamassKeep** [comment]
Ok perfect, so

This is two screen-capture where on the minimap you can see a straight border with other biomes but they are not real, when i continue to load the world, the bug fixes itself, but maybe it's important for you to know that, 

and now that i have fully test the generation of my actual world, i am sure that some time the generation continue normally but with a straight wall like the photo (explication) it's not a real photo but the same thing is happening, personnaly this is not a problem for me, so let's continue to play.

![explication](https://user-images.githubusercontent.com/106327919/170561157-7ef11d1f-47ba-4a31-a168-92d1c75cf889.jpg)

![New-world-test](https://user-images.githubusercontent.com/106327919/170559170-5e436d93-3b9e-400c-ab19-1d64bb7d0259.png)

![New-world-test2](https://user-images.githubusercontent.com/106327919/170559408-a0c7004c-f2a6-4bf5-99e8-cf8f131e4f99.png)

**Comment by KamassKeep** [comment]
sorry for the photo "explication" it's a photo from the past (no-hunger)

**Comment by MrFantiVideo** [comment]
This is just an update problem linked to the latest bugger version if I understood correctly? 
It's not very disturbing especially if it won't happen again in the next version.

**Comment by KamassKeep** [comment]
yes it is a problem link to the fact that i have updated the mods, so it's not really annoying, thanks for all.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.2](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.2))
