### ISSUE TITLE
Entities are floating over minecarts when riding them

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [MrFantiVideo/MineGate#31]
**MC** 1.18.2
**Fabric API** 0.53.4
**MineGate** 1.2.2

To reproduce:

1. Grab a rail and a minecart
2. Place a rail down, place a minecart down and sit in it
3. Observe that you are actually hovering over the minecart
![2022-05-30_20 25 00](https://user-images.githubusercontent.com/86702831/171044904-d084b255-be64-4c1c-8a11-34bbb6165d97.png)

Affects all entities, not just the player. This is not just a visual bug either, it actually affects entities' collision box, which makes them unable to move through 2 blocks tall railways. This potentially breaks farms that have entities riding minecarts in them.

Logs: https://gist.github.com/Footage2-Amply-Pounce/b8c696813d179441bf7a1e135ef335a1

**Comment by MrFantiVideo** [comment]
I will see to fix this problem before 1.19

**Comment by MrFantiVideo** [comment]
After checking on my side, I don't have this problem.

![image](https://user-images.githubusercontent.com/27833548/172111242-94754c56-492e-4e10-9b4d-920a4f88c52f.png)

Are you sure you don't have a mod that changes player size?

**Comment by MrFantiVideo** [comment]
As much for me, I was on my dev version and unwittingly I fixed the bug by modifying things.
This will be corrected in the next version.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.3](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.3))
_Note: An improvement in the future is planned, if other similar issues exist._
