### ISSUE TITLE
origins sizing doesn't work

### ISSUE THREAD

**Issue by the-crazy-diabetic** [MrFantiVideo/MineGate#32]
I have been using mods like [extraorigins](https://www.curseforge.com/minecraft/mc-mods/extra-origins) one of the origin's powers is being very small, but when I use minegate, the hitbox size doesn't change. when I removed minegate the power started working again.
without minegate
![2022-06-03_20 54 26](https://user-images.githubusercontent.com/103698441/171970252-4d659008-f167-4dcf-a0a5-acce60447f9d.png)
with minegate 
![2022-06-03_20 58 27](https://user-images.githubusercontent.com/103698441/171970360-d031c0e9-4649-4f0d-975b-5c79ef272ba4.png)

**Comment by the-crazy-diabetic** [comment]
this is in fabric 1.18.2 and [this](https://www.curseforge.com/minecraft/mc-mods/minegate-moreblocks/files/3807364) version of minegate

**Comment by MrFantiVideo** [comment]
MineGate also offers to change the size of entities with potions / effects / flowers.
To make it compatible with other mods, an option will be available in the next version.

I will keep you informed here.

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.3](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.3))
You must disable the « changeSize » option in the « minegate.json » if you want to use another mod that changes the size of entities.
