### ISSUE TITLE
Biome generation mods conflict and block drops don't work properly 1.17.1

### ISSUE THREAD

**Issue by godofwwa52000** [MrFantiVideo/MineGate#7]
I was having issued with the Williams Overhauled Overworld mod and I left a message on his mod page and he got back to me saying that this mod was the issue and linked me to a github issue page (https://github.com/MrFantiVideo/MineGate/issues/5). I removed his mod because I really like this mod, but I have another issue with this mod as well. I am on version 1.17.1, Fabric version 0.11.6, and this mod version 1.1.5. I have used an iron, diamond, and netherite pickaxe to mine your woodcutter and blocks the woodcutter makes, but it takes a really long time and doesn't drop the block. I would like to know if there is a plan to fix the conflicts with the generation mods so we don't have to choose between this and biome mods, and the issues with mining any block from this mod.

**Comment by godofwwa52000** [comment]
I just found another bug as well. I am not sure if it does this without and instant tree mining mods but with the 2 tree mining mods that are out for 1.17.1, Trees do not float and falling tree (I tried both because I thought it may have been an issue with the tree mod I had at the time), but whenever I instant mine a tree it drops all of the leaf blocks instead of saplings and sticks. And I cannot just place them down and rebreak them either, they still drop leaves like that as well. I removed this mod and it acts like normal again so it is for sure this one.

**Comment by GuyASmith** [comment]
Signal boosting that I'm also having problems with leaves just dropping as blocks instead of saplings and sticks, without any mods that alter trees/tree behaviour.

**Comment by godofwwa52000** [comment]
I just had to remove the mod since it was causing more issues than it's worth. Great mod, but it was causing me to remove other mods so this one eventually had to go.

**Comment by MrFantiVideo** [comment]
Hello,

You reported 3 known issues, 2 of which are already on Github in issues.

For the tree drop problem, a temporary solution is currently available [here](https://github.com/MrFantiVideo/MineGate/issues/6).
I had pinned the issue precisely to avoid duplicates.

For the compatibility concerns with other mods, the problem has been reported on the issue [here](https://github.com/MrFantiVideo/MineGate/issues/5#issuecomment-884909048).
The solution is to disable mixins with the new mod option.

Finally, the problem with block breaking to be signaled on Discord, I invite you to go there if you need a quick answer.
All problems are corrected in the new version. ([MoreBlocks 1.1.6](https://github.com/MrFantiVideo/MineGate/releases/tag/1.1.6))

Thank you for your contribution and sorry for the occasional inconvenience this may have caused.

Have a good day :)
