### ISSUE TITLE
All tree types drop apples

### ISSUE THREAD

**Issue by BlueThunderFox** [MrFantiVideo/MineGate#8]
Birch Wood trees and Spruce Wood trees (and maybe other types) drop apples from their leaves, and should not.  Only "Oak and dark oak leaves have 0.5% (1⁄200) chance of dropping an apple when decayed or broken." -Minecraft wiki

Please verify that only Oak and Dark Oak tree leaves drop apples.

**Comment by MrFantiVideo** [comment]
Hello,

All problems are corrected in the new version. ([MoreBlocks 1.1.7](https://github.com/MrFantiVideo/MineGate/releases/tag/1.1.7))

Thank you for your contribution and sorry for the occasional inconvenience this may have caused.

Have a good day :)
