### ISSUE TITLE
Can't use new stick types to craft some items

### ISSUE THREAD

**Issue by BlueThunderFox** [MrFantiVideo/MineGate#9]
Can't use special stick types (example: Birch Sticks) to craft the following:
-Paintings
-Item frames
-Campfires
-Armor stands
-Banners
-Grindstone

Please verify that these items are craftable with birch wood sticks, and all other types.

**Comment by MrFantiVideo** [comment]
Hello,

All problems are corrected in the new version. ([MoreBlocks 1.1.7](https://github.com/MrFantiVideo/MineGate/releases/tag/1.1.7))

Thank you for your contribution and sorry for the occasional inconvenience this may have caused.

Have a good day :)
